'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

'<Assembly: Elegant.Ui.CommandSourceAttribute("MC_Parroquial.ApplicationCommands", "MC_Parroquial.MC_Parroquial.ApplicationCommands")> 
'Namespace MC_Parroquial

' This class is required for commands suppport.
' Do not modify this code inside the editor.

Public Class ApplicationCommands

    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")> Public Shared cmSalir As Elegant.Ui.Command = New Elegant.Ui.Command("cmSalir")
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")> Public Shared cmdBautismo As Elegant.Ui.Command = New Elegant.Ui.Command("cmdBautismo")
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")> Public Shared cmdConfirmacion As Elegant.Ui.Command = New Elegant.Ui.Command("cmdConfirmacion")
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")> Public Shared cmdMatrimonio As Elegant.Ui.Command = New Elegant.Ui.Command("cmdMatrimonio")
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")> Public Shared cmdCerrarFormulario As Elegant.Ui.Command = New Elegant.Ui.Command("cmdCerrarFormulario")

    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")> Public Shared cmdBuscarBautismo As Elegant.Ui.Command = New Elegant.Ui.Command("cmdBuscarBautismo")

    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")> Public Shared cmdCertificado As Elegant.Ui.Command = New Elegant.Ui.Command("cmdCertificado")

End Class


'End Namespace

